# Site settings
title: Hardin & Erna
email: wedding@hardinanderna.com
description: We are tying the knot!
keyword: Hardin, Erna, Wedding, Nikah, Kahwin, Solemnization, Hardin & Erna
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hardinanderna.com" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, webpack, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]